// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfoDTO describes static application info for the settings GUI
 */
export class AppInfoDTO {
    "version": string;
    "configPath": string;
    "resolvedLanguage": string;
    "platform": string;
    "specialTargets": string[];
    "autostartAvailable": boolean;

    /** Creates a new AppInfoDTO instance. */
    constructor($$source: Partial<AppInfoDTO> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("resolvedLanguage" in $$source)) {
            this["resolvedLanguage"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("specialTargets" in $$source)) {
            this["specialTargets"] = [];
        }
        if (!("autostartAvailable" in $$source)) {
            this["autostartAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfoDTO {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("specialTargets" in $$parsedSource) {
            $$parsedSource["specialTargets"] = $$createField4_0($$parsedSource["specialTargets"]);
        }
        return new AppInfoDTO($$parsedSource as Partial<AppInfoDTO>);
    }
}

/**
 * COMSettings describes the Arduino serial connection parameters
 */
export class COMSettings {
    "port": string;
    "baudRate": number;
    "vid": HexWord;
    "pid": HexWord;

    /** Creates a new COMSettings instance. */
    constructor($$source: Partial<COMSettings> = {}) {
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("baudRate" in $$source)) {
            this["baudRate"] = 0;
        }
        if (!("vid" in $$source)) {
            this["vid"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new COMSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): COMSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new COMSettings($$parsedSource as Partial<COMSettings>);
    }
}

/**
 * DiscordSettings describes the Discord RPC integration. deej can't ship
 * credentials of its own: Discord gates the rpc.voice.* scopes to an
 * application's owner, so the user creates their own application and pastes
 * its ID and secret here. The OAuth token that comes out of linking is not
 * kept here - it lives in its own file next to the config (see discord.go)
 */
export class DiscordSettings {
    "enabled": boolean;
    "clientId": string;
    "clientSecret": string;
    "volumeConversion": boolean;

    /** Creates a new DiscordSettings instance. */
    constructor($$source: Partial<DiscordSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("clientSecret" in $$source)) {
            this["clientSecret"] = "";
        }
        if (!("volumeConversion" in $$source)) {
            this["volumeConversion"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscordSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscordSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscordSettings($$parsedSource as Partial<DiscordSettings>);
    }
}

/**
 * DiscordStatusDTO describes the Discord integration's state for the settings GUI
 */
export class DiscordStatusDTO {
    /**
     * an account has been authorized
     */
    "linked": boolean;

    /**
     * the RPC connection is up
     */
    "connected": boolean;

    /**
     * the voice channel the user is in, if any
     */
    "channel": string;

    /** Creates a new DiscordStatusDTO instance. */
    constructor($$source: Partial<DiscordStatusDTO> = {}) {
        if (!("linked" in $$source)) {
            this["linked"] = false;
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscordStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscordStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscordStatusDTO($$parsedSource as Partial<DiscordStatusDTO>);
    }
}

/**
 * DiscordUserDTO describes one member of the current voice channel
 */
export class DiscordUserDTO {
    "id": string;
    "name": string;

    /** Creates a new DiscordUserDTO instance. */
    constructor($$source: Partial<DiscordUserDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscordUserDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscordUserDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscordUserDTO($$parsedSource as Partial<DiscordUserDTO>);
    }
}

/**
 * HexWord is a 16-bit value carried as a hex string (e.g. "1A86"), the form
 * both the config file and the GUI use. An empty value means "use the
 * built-in default"
 */
export type HexWord = string;

/**
 * OBSSettings describes the OBS websocket connection parameters
 */
export class OBSSettings {
    "enabled": boolean;
    "host": string;
    "port": number;
    "password": string;
    "volumeConversion": boolean;

    /** Creates a new OBSSettings instance. */
    constructor($$source: Partial<OBSSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("volumeConversion" in $$source)) {
            this["volumeConversion"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OBSSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): OBSSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OBSSettings($$parsedSource as Partial<OBSSettings>);
    }
}

/**
 * Profile is one named slider layout. Only the mapping and its hotkey are
 * per-profile; everything else (com, obs, language, ...) stays global.
 * normalize guarantees at least one profile exists, so consumers can always
 * resolve a mapping
 */
export class Profile {
    "name": string;
    "hotkey": string;
    "sliderMapping": SliderMappings;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hotkey" in $$source)) {
            this["hotkey"] = "";
        }
        if (!("sliderMapping" in $$source)) {
            this["sliderMapping"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sliderMapping" in $$parsedSource) {
            $$parsedSource["sliderMapping"] = $$createField2_0($$parsedSource["sliderMapping"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

/**
 * SerialPortDTO describes an available serial port
 */
export class SerialPortDTO {
    "name": string;
    "isUsb": boolean;
    "vid": string;
    "pid": string;
    "product": string;

    /** Creates a new SerialPortDTO instance. */
    constructor($$source: Partial<SerialPortDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isUsb" in $$source)) {
            this["isUsb"] = false;
        }
        if (!("vid" in $$source)) {
            this["vid"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = "";
        }
        if (!("product" in $$source)) {
            this["product"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SerialPortDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortDTO($$parsedSource as Partial<SerialPortDTO>);
    }
}

/**
 * SessionInfoDTO describes a running audio session for target suggestions
 */
export class SessionInfoDTO {
    "key": string;

    /**
     * friendly name, may be empty
     */
    "displayName": string;

    /**
     * device master session, not a process
     */
    "isDevice": boolean;

    /**
     * capture-side session (microphone)
     */
    "isInput": boolean;

    /** Creates a new SessionInfoDTO instance. */
    constructor($$source: Partial<SessionInfoDTO> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("isDevice" in $$source)) {
            this["isDevice"] = false;
        }
        if (!("isInput" in $$source)) {
            this["isInput"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfoDTO($$parsedSource as Partial<SessionInfoDTO>);
    }
}

/**
 * Settings is the single source of truth for deej's user-facing
 * configuration. The yaml tags define the config file keys, the json tags
 * the GUI wire format: a new setting only needs a field here (plus a default
 * in defaultSettings and, if needed, a rule in normalize) to reach the file,
 * the runtime snapshot and the settings GUI
 */
export class Settings {
    "activeProfile": string;
    "profiles": Profile[];
    "invertSliders": boolean;
    "com": COMSettings;
    "noiseReduction": string;
    "language": string;
    "obs": OBSSettings;
    "discord": DiscordSettings;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("activeProfile" in $$source)) {
            this["activeProfile"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("invertSliders" in $$source)) {
            this["invertSliders"] = false;
        }
        if (!("com" in $$source)) {
            this["com"] = (new COMSettings());
        }
        if (!("noiseReduction" in $$source)) {
            this["noiseReduction"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("obs" in $$source)) {
            this["obs"] = (new OBSSettings());
        }
        if (!("discord" in $$source)) {
            this["discord"] = (new DiscordSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        if ("com" in $$parsedSource) {
            $$parsedSource["com"] = $$createField3_0($$parsedSource["com"]);
        }
        if ("obs" in $$parsedSource) {
            $$parsedSource["obs"] = $$createField6_0($$parsedSource["obs"]);
        }
        if ("discord" in $$parsedSource) {
            $$parsedSource["discord"] = $$createField7_0($$parsedSource["discord"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SliderMappingEntry is one slider's targets, JSON-friendly for the GUI
 */
export class SliderMappingEntry {
    "slider": number;
    "targets": string[];

    /** Creates a new SliderMappingEntry instance. */
    constructor($$source: Partial<SliderMappingEntry> = {}) {
        if (!("slider" in $$source)) {
            this["slider"] = 0;
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SliderMappingEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SliderMappingEntry {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new SliderMappingEntry($$parsedSource as Partial<SliderMappingEntry>);
    }
}

/**
 * SliderMappings is the slider_mapping config key. In the file it's a YAML
 * mapping of slider index to a single target or a list of targets
 */
export type SliderMappings = SliderMappingEntry[];

/**
 * StatusDTO describes the live connection state for the settings GUI
 */
export class StatusDTO {
    "connected": boolean;
    "comPort": string;

    /**
     * 0..1, as sessions receive them
     */
    "sliderValues": number[];

    /** Creates a new StatusDTO instance. */
    constructor($$source: Partial<StatusDTO> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("comPort" in $$source)) {
            this["comPort"] = "";
        }
        if (!("sliderValues" in $$source)) {
            this["sliderValues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusDTO {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sliderValues" in $$parsedSource) {
            $$parsedSource["sliderValues"] = $$createField2_0($$parsedSource["sliderValues"]);
        }
        return new StatusDTO($$parsedSource as Partial<StatusDTO>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
var $$createType1 = (function $$initCreateType1(...args: any[]): any {
    if ($$createType1 === $$initCreateType1) {
        $$createType1 = $$createType3;
    }
    return $$createType1(...args);
});
const $$createType2 = SliderMappingEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Profile.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = COMSettings.createFrom;
const $$createType7 = OBSSettings.createFrom;
const $$createType8 = DiscordSettings.createFrom;
const $$createType9 = $Create.Array($Create.Any);
