// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfoDTO describes static application info for the settings GUI
 */
export class AppInfoDTO {
    "version": string;
    "configPath": string;
    "resolvedLanguage": string;
    "specialTargets": string[];

    /** Creates a new AppInfoDTO instance. */
    constructor($$source: Partial<AppInfoDTO> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("resolvedLanguage" in $$source)) {
            this["resolvedLanguage"] = "";
        }
        if (!("specialTargets" in $$source)) {
            this["specialTargets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfoDTO {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("specialTargets" in $$parsedSource) {
            $$parsedSource["specialTargets"] = $$createField3_0($$parsedSource["specialTargets"]);
        }
        return new AppInfoDTO($$parsedSource as Partial<AppInfoDTO>);
    }
}

/**
 * SerialPortDTO describes an available serial port
 */
export class SerialPortDTO {
    "name": string;
    "isUsb": boolean;
    "vid": string;
    "pid": string;
    "product": string;

    /** Creates a new SerialPortDTO instance. */
    constructor($$source: Partial<SerialPortDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isUsb" in $$source)) {
            this["isUsb"] = false;
        }
        if (!("vid" in $$source)) {
            this["vid"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = "";
        }
        if (!("product" in $$source)) {
            this["product"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SerialPortDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortDTO($$parsedSource as Partial<SerialPortDTO>);
    }
}

/**
 * SessionInfoDTO describes a running audio session for target suggestions
 */
export class SessionInfoDTO {
    "key": string;

    /**
     * friendly name, may be empty
     */
    "displayName": string;

    /** Creates a new SessionInfoDTO instance. */
    constructor($$source: Partial<SessionInfoDTO> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfoDTO($$parsedSource as Partial<SessionInfoDTO>);
    }
}

/**
 * SettingsDTO is a JSON-friendly mirror of the user config file, used by the settings GUI
 */
export class SettingsDTO {
    "comPort": string;
    "baudRate": number;

    /**
     * 16-bit hex string, e.g. "1A86"
     */
    "comVid": string;
    "comPid": string;
    "invertSliders": boolean;
    "noiseReduction": string;
    "language": string;
    "obsEnabled": boolean;
    "obsHost": string;
    "obsPort": number;
    "obsPassword": string;
    "sliderMapping": SliderMappingEntry[];

    /** Creates a new SettingsDTO instance. */
    constructor($$source: Partial<SettingsDTO> = {}) {
        if (!("comPort" in $$source)) {
            this["comPort"] = "";
        }
        if (!("baudRate" in $$source)) {
            this["baudRate"] = 0;
        }
        if (!("comVid" in $$source)) {
            this["comVid"] = "";
        }
        if (!("comPid" in $$source)) {
            this["comPid"] = "";
        }
        if (!("invertSliders" in $$source)) {
            this["invertSliders"] = false;
        }
        if (!("noiseReduction" in $$source)) {
            this["noiseReduction"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("obsEnabled" in $$source)) {
            this["obsEnabled"] = false;
        }
        if (!("obsHost" in $$source)) {
            this["obsHost"] = "";
        }
        if (!("obsPort" in $$source)) {
            this["obsPort"] = 0;
        }
        if (!("obsPassword" in $$source)) {
            this["obsPassword"] = "";
        }
        if (!("sliderMapping" in $$source)) {
            this["sliderMapping"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsDTO {
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sliderMapping" in $$parsedSource) {
            $$parsedSource["sliderMapping"] = $$createField11_0($$parsedSource["sliderMapping"]);
        }
        return new SettingsDTO($$parsedSource as Partial<SettingsDTO>);
    }
}

/**
 * SliderMappingEntry is a JSON-friendly representation of a single slider's targets
 */
export class SliderMappingEntry {
    "slider": number;
    "targets": string[];

    /** Creates a new SliderMappingEntry instance. */
    constructor($$source: Partial<SliderMappingEntry> = {}) {
        if (!("slider" in $$source)) {
            this["slider"] = 0;
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SliderMappingEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SliderMappingEntry {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new SliderMappingEntry($$parsedSource as Partial<SliderMappingEntry>);
    }
}

/**
 * StatusDTO describes the live connection state for the settings GUI
 */
export class StatusDTO {
    "connected": boolean;
    "comPort": string;

    /**
     * 0..1, as sessions receive them
     */
    "sliderValues": number[];

    /** Creates a new StatusDTO instance. */
    constructor($$source: Partial<StatusDTO> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("comPort" in $$source)) {
            this["comPort"] = "";
        }
        if (!("sliderValues" in $$source)) {
            this["sliderValues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusDTO {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sliderValues" in $$parsedSource) {
            $$parsedSource["sliderValues"] = $$createField2_0($$parsedSource["sliderValues"]);
        }
        return new StatusDTO($$parsedSource as Partial<StatusDTO>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SliderMappingEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
