// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes configuration APIs to the settings GUI frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppInfo returns version and localization info along with the list of
 * special slider targets deej supports
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfoDTO> {
    return $Call.ByID(1852388263).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAutostart reports whether deej is set to run at system startup
 */
export function GetAutostart(): $CancellablePromise<boolean> {
    return $Call.ByID(3740953349);
}

/**
 * GetDiscordStatus returns the Discord integration's live state
 */
export function GetDiscordStatus(): $CancellablePromise<$models.DiscordStatusDTO> {
    return $Call.ByID(2917961514).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDiscordUsers returns the members of the voice channel the user is
 * currently in, for slider mapping suggestions. The roster is kept current by
 * RPC events, so this serves it as-is; the GUI is told to re-read it by the
 * deej:discord event rather than by polling
 */
export function GetDiscordUsers(): $CancellablePromise<$models.DiscordUserDTO[]> {
    return $Call.ByID(96084360).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetOBSInputs returns the input names of the connected OBS instance, for
 * slider mapping suggestions
 */
export function GetOBSInputs(): $CancellablePromise<string[]> {
    return $Call.ByID(1620740735).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetProcessIcons returns PNG data URIs for the icons of the given process
 * names, keyed by the names exactly as passed. Icons are cached across calls
 */
export function GetProcessIcons(names: string[]): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3155775785, names).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetProcesses returns the deduplicated, sorted executable names of all
 * running processes
 */
export function GetProcesses(): $CancellablePromise<string[]> {
    return $Call.ByID(3688174489).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSessions returns the current audio sessions with friendly display
 * names, for slider mapping suggestions
 */
export function GetSessions(): $CancellablePromise<$models.SessionInfoDTO[]> {
    return $Call.ByID(1202968053).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSettings returns the current contents of the user config file
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1935164325).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetStatus returns the current serial connection state and slider values,
 * so the settings window doesn't have to wait for the first live event
 */
export function GetStatus(): $CancellablePromise<$models.StatusDTO> {
    return $Call.ByID(4223089242).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * LinkDiscord runs the interactive authorization. Discord shows the user a
 * consent dialog, so this blocks until they answer it (or time out)
 */
export function LinkDiscord(): $CancellablePromise<void> {
    return $Call.ByID(656445116);
}

/**
 * ListSerialPorts enumerates the serial ports available on this machine
 */
export function ListSerialPorts(): $CancellablePromise<$models.SerialPortDTO[]> {
    return $Call.ByID(102515344).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SaveSettings validates and writes the given settings to the user config
 * file, applying them immediately
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(523154580, settings);
}

/**
 * SetActiveProfile switches to the named profile. It's a targeted write, so a
 * switch can't clobber a hand edit that landed since the window was opened
 */
export function SetActiveProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(1627894027, name);
}

/**
 * SetAutostart enables or disables running deej at system startup, applying
 * the change immediately
 */
export function SetAutostart(state: boolean): $CancellablePromise<void> {
    return $Call.ByID(470775857, state);
}

/**
 * UnlinkDiscord forgets the stored authorization
 */
export function UnlinkDiscord(): $CancellablePromise<void> {
    return $Call.ByID(235581697);
}

// Private type creation functions
const $$createType0 = $models.AppInfoDTO.createFrom;
const $$createType1 = $models.DiscordStatusDTO.createFrom;
const $$createType2 = $models.DiscordUserDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $models.SessionInfoDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.Settings.createFrom;
const $$createType9 = $models.StatusDTO.createFrom;
const $$createType10 = $models.SerialPortDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
