// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes configuration APIs to the settings GUI frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppInfo returns version and localization info along with the list of
 * special slider targets deej supports
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfoDTO> {
    return $Call.ByID(1852388263).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetOBSInputs returns the input names of the connected OBS instance, for
 * slider mapping suggestions
 */
export function GetOBSInputs(): $CancellablePromise<string[]> {
    return $Call.ByID(1620740735).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSessions returns the current audio sessions with friendly display
 * names, for slider mapping suggestions
 */
export function GetSessions(): $CancellablePromise<$models.SessionInfoDTO[]> {
    return $Call.ByID(1202968053).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSettings returns the current contents of the user config file
 */
export function GetSettings(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(1935164325).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetStatus returns the current serial connection state and slider values,
 * so the settings window doesn't have to wait for the first live event
 */
export function GetStatus(): $CancellablePromise<$models.StatusDTO> {
    return $Call.ByID(4223089242).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListSerialPorts enumerates the serial ports available on this machine
 */
export function ListSerialPorts(): $CancellablePromise<$models.SerialPortDTO[]> {
    return $Call.ByID(102515344).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SaveSettings validates and writes the given settings to the user config
 * file, applying them immediately
 */
export function SaveSettings(dto: $models.SettingsDTO): $CancellablePromise<void> {
    return $Call.ByID(523154580, dto);
}

// Private type creation functions
const $$createType0 = $models.AppInfoDTO.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.SessionInfoDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SettingsDTO.createFrom;
const $$createType5 = $models.StatusDTO.createFrom;
const $$createType6 = $models.SerialPortDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
